import type { Listing } from "./types";

export const mockListings: Listing[] = [
  {
    id: "ca-101",
    address: "123 Maple Street",
    city: "Sacramento",
    state: "CA",
    zip: "95814",
    price: 545000,
    beds: 3,
    baths: 2,
    sqft: 1680,
    propertyType: "single-family",
    yearBuilt: 1998,
    daysOnMarket: 5,
    description:
      "Bright single-story home with an updated kitchen and a low-maintenance backyard.",
    isSample: true,
  },
  {
    id: "ca-102",
    address: "48 Birch Lane",
    city: "San Diego",
    state: "CA",
    zip: "92103",
    price: 879000,
    beds: 2,
    baths: 2,
    sqft: 1120,
    propertyType: "condo",
    yearBuilt: 2015,
    daysOnMarket: 12,
    description:
      "Modern corner condo with floor-to-ceiling windows and a walkable downtown location.",
    isSample: true,
  },
  {
    id: "ca-103",
    address: "907 Cedar Court",
    city: "San Jose",
    state: "CA",
    zip: "95126",
    price: 1185000,
    beds: 4,
    baths: 3,
    sqft: 2450,
    propertyType: "single-family",
    yearBuilt: 2007,
    daysOnMarket: 68,
    description:
      "Spacious family home with a flexible bonus room and a sunny open floor plan.",
    isSample: true,
  },
  {
    id: "tx-201",
    address: "12 Willow Way",
    city: "Austin",
    state: "TX",
    zip: "78704",
    price: 625000,
    beds: 3,
    baths: 2.5,
    sqft: 1950,
    propertyType: "townhouse",
    yearBuilt: 2019,
    daysOnMarket: 3,
    description:
      "Sleek three-level townhouse with a rooftop terrace and an attached two-car garage.",
    isSample: true,
  },
  {
    id: "tx-202",
    address: "330 Oak Ridge Drive",
    city: "Houston",
    state: "TX",
    zip: "77019",
    price: 410000,
    beds: 4,
    baths: 3,
    sqft: 2280,
    propertyType: "single-family",
    yearBuilt: 1995,
    daysOnMarket: 41,
    description:
      "Roomy four-bedroom home with a large covered patio and a freshly landscaped yard.",
    isSample: true,
  },
  {
    id: "tx-203",
    address: "75 Pecan Grove Boulevard",
    city: "Dallas",
    state: "TX",
    zip: "75204",
    price: 295000,
    beds: 2,
    baths: 1,
    sqft: 980,
    propertyType: "condo",
    yearBuilt: 1984,
    daysOnMarket: 90,
    description:
      "Cozy starter condo with in-unit laundry and easy access to nearby shops.",
    isSample: true,
  },
  {
    id: "fl-301",
    address: "58 Palm Avenue",
    city: "Orlando",
    state: "FL",
    zip: "32801",
    price: 365000,
    beds: 3,
    baths: 2,
    sqft: 1540,
    propertyType: "single-family",
    yearBuilt: 2003,
    daysOnMarket: 18,
    description:
      "Well-kept home with a screened lanai and an open kitchen that flows to the living area.",
    isSample: true,
  },
  {
    id: "fl-302",
    address: "214 Coral Street",
    city: "Tampa",
    state: "FL",
    zip: "33606",
    price: 489000,
    beds: 3,
    baths: 2.5,
    sqft: 1820,
    propertyType: "townhouse",
    yearBuilt: 2018,
    daysOnMarket: 7,
    description:
      "Bright townhouse with high ceilings, a private courtyard, and a community pool.",
    isSample: true,
  },
  {
    id: "fl-303",
    address: "9 Seabreeze Lane",
    city: "Miami",
    state: "FL",
    zip: "33133",
    price: 740000,
    beds: 4,
    baths: 4,
    sqft: 3100,
    propertyType: "multi-family",
    yearBuilt: 1972,
    daysOnMarket: 55,
    description:
      "Versatile duplex offering two updated units, ideal for owner-occupants or investors.",
    isSample: true,
  },
  {
    id: "ny-401",
    address: "604 Elm Street",
    city: "Buffalo",
    state: "NY",
    zip: "14209",
    price: 232000,
    beds: 3,
    baths: 1.5,
    sqft: 1460,
    propertyType: "single-family",
    yearBuilt: 1951,
    daysOnMarket: 33,
    description:
      "Charming classic home with original hardwood floors and a deep fenced backyard.",
    isSample: true,
  },
  {
    id: "il-501",
    address: "1820 Lakeview Place",
    city: "Chicago",
    state: "IL",
    zip: "60614",
    price: 560000,
    beds: 2,
    baths: 2,
    sqft: 1250,
    propertyType: "condo",
    yearBuilt: 2010,
    daysOnMarket: 22,
    description:
      "Stylish condo with an open layout, a private balcony, and secured building parking.",
    isSample: true,
  },
  {
    id: "wa-601",
    address: "37 Spruce Hill Road",
    city: "Seattle",
    state: "WA",
    zip: "98115",
    price: 925000,
    beds: 4,
    baths: 2.5,
    sqft: 2360,
    propertyType: "single-family",
    yearBuilt: 1989,
    daysOnMarket: 9,
    description:
      "Light-filled craftsman with a remodeled kitchen and a detached home-office studio.",
    isSample: true,
  },
  {
    id: "co-701",
    address: "455 Aspen Trail",
    city: "Denver",
    state: "CO",
    zip: "80205",
    price: 615000,
    beds: 3,
    baths: 3,
    sqft: 1900,
    propertyType: "townhouse",
    yearBuilt: 2016,
    daysOnMarket: 4,
    description:
      "Contemporary townhouse with mountain views, a two-car garage, and a flexible loft.",
    isSample: true,
  },
  {
    id: "ga-801",
    address: "26 Magnolia Court",
    city: "Atlanta",
    state: "GA",
    zip: "30312",
    price: 398000,
    beds: 3,
    baths: 2,
    sqft: 1720,
    propertyType: "single-family",
    yearBuilt: 2001,
    daysOnMarket: 47,
    description:
      "Inviting brick home with a covered front porch and an updated primary suite.",
    isSample: true,
  },
  {
    id: "nc-901",
    address: "112 Dogwood Drive",
    city: "Charlotte",
    state: "NC",
    zip: "28203",
    price: 345000,
    beds: 1,
    baths: 1,
    sqft: 640,
    propertyType: "condo",
    yearBuilt: 2021,
    daysOnMarket: 75,
    description:
      "Efficient one-bedroom condo with smart finishes and a fitness center on site.",
    isSample: true,
  },
  {
    id: "az-1001",
    address: "880 Saguaro Street",
    city: "Phoenix",
    state: "AZ",
    zip: "85016",
    price: 1090000,
    beds: 6,
    baths: 5,
    sqft: 4480,
    propertyType: "multi-family",
    yearBuilt: 2024,
    daysOnMarket: 2,
    description:
      "Newly built triplex with three turnkey units and shared off-street parking.",
    isSample: true,
  },
];
